// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysvlxmvidynzhhiinksj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlzdmx4bXZpZHluemhoaWlua3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1Nzk0OTMsImV4cCI6MjA3MzE1NTQ5M30.GAwaMfg1MU4AYvuzQpTiA27wDM3D9s-Y7oOhNBmqdDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});